### ISSUE TITLE
App posted on Google Play, does not mention location of source

### ISSUE THREAD

**Issue by brarcher** [zikalify/BMI_Calculator#3]
I noticed on the Google Play store that a BMI application with your same application ID, namely com.zola.bmi, is posted under the author Jolly Crab Studios.

https://play.google.com/store/apps/details?id=com.zola.bmi

I suspect that you did not authorize this developer to publish your work under their name, especially in violation of the GPLv3 as no link to the source code is provided. This developer did the same with another of my applications.

If you are interested, you may choose to ask Google to take down this application, if that is your wish.

https://support.google.com/legal/contact/lr_dmca?product=googleplay

FYI.

**Comment by zikalify** [comment]
It seems to be gone

**Comment by brarcher** [comment]
I reported to Google that the developer in question was not following Google's rules, and I believe they disabled the developer's account. So, the problem seemed to have solved itself for you. (:
